// Compile command: gcc 00.1-get-char.c -g -o 00.1-get-char.out

#include <stdio.h>

int main()
{
    long nc = 0;
    
    // The EOF marker is a signal that there is no more data to be read from the input stream.
    // It is typically generated by the operating system or the terminal environment when you
    //      indicate the end of input through a special key combination or command,
    //      such as Ctrl+D (on Unix-like systems) or Ctrl+Z and Enter (on Windows).
    
    while (getchar() != EOF)    // Not the same as gets()
        nc++;
    printf("%ld\n", nc);        // Also counts '\n' chars
    
    return 0;
}

