// Compile command: gcc 00.3-gets-fgets.c -g -o 00.3-gets-fgets.out

#include <stdio.h>
#include <string.h>

int main()
{
    long nc = 0;
    long nl = 0;
    char s[256];
    
    // The EOF marker is a signal that there is no more data to be read from the input stream.
    // It is typically generated by the operating system or the terminal environment when you
    //      indicate the end of input through a special key combination or command,
    //      such as Ctrl+D (on Unix-like systems) or Ctrl+Z and Enter (on Windows).
    
    // fgets() is generally considered safer than gets() because it allows you to specify
    //      the maximum number of characters to read and prevents buffer overflow vulnerabilities.
    //      Additionally, fgets() provides more control over the handling of newline characters
    //      in the input string. Therefore, it's recommended to use fgets() instead of gets()
    //      for reading strings from stdin in C programs.
    
    for (; fgets(s, sizeof(s), stdin) != NULL; nc += strlen(s), nl++) {}
    
    printf("%ld %ld\n", nc, nl);            // Also counts '\n' chars
        
    return 0;
}

