// Compile command: gcc 02-contar-palavras-diferentes.c -o 02-contar-palavras-diferentes.out

// The EOF marker is a signal that there is no more data to be read from the input stream.
// It is typically generated by the operating system or the terminal environment when you
//      indicate the end of input through a special key combination or command,
//      such as Ctrl+D (on Unix-like systems) or Ctrl+Z (on Windows).

// fgets() is generally considered safer than gets() because it allows you to specify
//      the maximum number of characters to read and prevents buffer overflow vulnerabilities.
//      Additionally, fgets() provides more control over the handling of newline characters
//      in the input string. Therefore, it's recommended to use fgets() instead of gets()
//      for reading strings from stdin in C programs.
    
#include <stdio.h>
#include <ctype.h>
#include <string.h>     // for strlen()
#include <stdlib.h>     // needed for malloc();

// Uma sequência de caracteres brancos
int ReadWord_1(FILE *f, char *s)
{
    int c;
    while (c = getc(f), !isspace(c))
        *s++ = c;
    *s = '\0';
    return ungetc(c, f);    // Puts back the last read char and returns c
}

// Uma sequência de letras e hífenes
int ReadWord(FILE *f, char *s)
{
    int c;
    while (c = getc(f), !isalpha(c) || c == '-')
        *s++ = c;
    *s = '\0';
    return ungetc(c, f);    // c is forgoten and thus needs to be given
}

// Uma sequência de letras, algarismos e sublinhados
int ReadWord_3(FILE *f, char *s)
{
    int c;
    while (c = getc(f), isalnum(c) || c == '_')
        *s++ = c;
    *s = '\0';
    return ungetc(c, f);
}

// Para uma sequência de letras e hífenes
int SkipChars(FILE *f, int *n)
{
    int c;
    int k = 0;
    while ((c = getc(f)) != '\n' &&
           (isspace(c) || isdigit(c) ||
            ispunct(c) && c != '-'))
        k++;
    *n = k;
    return ungetc(c, f);
}

#define MAX_WORDS 1024
char *words[MAX_WORDS];
long n_words;
long n_unique;

char *ExistsWord(char *s)
{
    char **p;
    for (p = words; *p != NULL && strcmp(*p, s); p++) {}
    return *p;
}

char *strnew(const char *s)
{
    //                                    + 1 is the extra char for '\0'
    return strcpy((char*)malloc(strlen(s) + 1), s);
}

int main()
{
    int c, n;
    char s[256];
    
    // Stdin will not flush input characters onto the input stream until the newline character '\n'.
    //     So getc(stdin) has nothing to read until you hit enter. If you want to read the console
    //     input without hitting enter, you can use getch() function in conio.h library available
    //     with Windows compilers. getch() reads a character from stdin without waiting for a newline.

    n_unique = n_words = 0;
    while (ungetc(getchar(), stdin) != EOF)  // EOF is the same as -1
    {
        while (c = SkipChars(stdin, &n),
               c != '\n')  // The condition for the while, last one after ","
        {
            ReadWord(stdin, s);
            n_words++;
            if (ExistsWord(s) == NULL)
                words[n_unique++] = strnew(s);
        }
        getchar();
    }
    
    printf("%ld %ld\n", n_words, n_unique);
        
    return 0;
}

